// Generated by gencpp from file node_example/TopologicalMap.msg
// DO NOT EDIT!


#ifndef NODE_EXAMPLE_MESSAGE_TOPOLOGICALMAP_H
#define NODE_EXAMPLE_MESSAGE_TOPOLOGICALMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <node_example/TopologicalNode.h>
#include <node_example/TopologicalEdge.h>

namespace node_example
{
template <class ContainerAllocator>
struct TopologicalMap_
{
  typedef TopologicalMap_<ContainerAllocator> Type;

  TopologicalMap_()
    : header()
    , node_count(0)
    , node()
    , edge_count(0)
    , edge()  {
    }
  TopologicalMap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , node_count(0)
    , node(_alloc)
    , edge_count(0)
    , edge(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _node_count_type;
  _node_count_type node_count;

   typedef std::vector< ::node_example::TopologicalNode_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::node_example::TopologicalNode_<ContainerAllocator> >::other >  _node_type;
  _node_type node;

   typedef uint32_t _edge_count_type;
  _edge_count_type edge_count;

   typedef std::vector< ::node_example::TopologicalEdge_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::node_example::TopologicalEdge_<ContainerAllocator> >::other >  _edge_type;
  _edge_type edge;




  typedef boost::shared_ptr< ::node_example::TopologicalMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_example::TopologicalMap_<ContainerAllocator> const> ConstPtr;

}; // struct TopologicalMap_

typedef ::node_example::TopologicalMap_<std::allocator<void> > TopologicalMap;

typedef boost::shared_ptr< ::node_example::TopologicalMap > TopologicalMapPtr;
typedef boost::shared_ptr< ::node_example::TopologicalMap const> TopologicalMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_example::TopologicalMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_example::TopologicalMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_example

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'node_example': ['/home/younes/Images/ratslam_test/rospyy/src/node_example/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_example::TopologicalMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_example::TopologicalMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_example::TopologicalMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_example::TopologicalMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_example::TopologicalMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_example::TopologicalMap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_example::TopologicalMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deefb2c5a22caaa16af4e1b64a821bdc";
  }

  static const char* value(const ::node_example::TopologicalMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdeefb2c5a22caaa1ULL;
  static const uint64_t static_value2 = 0x6af4e1b64a821bdcULL;
};

template<class ContainerAllocator>
struct DataType< ::node_example::TopologicalMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_example/TopologicalMap";
  }

  static const char* value(const ::node_example::TopologicalMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_example::TopologicalMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 node_count\n\
TopologicalNode[] node\n\
uint32 edge_count\n\
TopologicalEdge[] edge\n\
\n\
	\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: node_example/TopologicalNode\n\
uint32 id\n\
geometry_msgs/Pose pose\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: node_example/TopologicalEdge\n\
uint32 id\n\
uint32 source_id\n\
uint32 destination_id\n\
duration duration\n\
geometry_msgs/Transform transform\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::node_example::TopologicalMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_example::TopologicalMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.node_count);
      stream.next(m.node);
      stream.next(m.edge_count);
      stream.next(m.edge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TopologicalMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_example::TopologicalMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_example::TopologicalMap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "node_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.node_count);
    s << indent << "node[]" << std::endl;
    for (size_t i = 0; i < v.node.size(); ++i)
    {
      s << indent << "  node[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::node_example::TopologicalNode_<ContainerAllocator> >::stream(s, indent + "    ", v.node[i]);
    }
    s << indent << "edge_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.edge_count);
    s << indent << "edge[]" << std::endl;
    for (size_t i = 0; i < v.edge.size(); ++i)
    {
      s << indent << "  edge[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::node_example::TopologicalEdge_<ContainerAllocator> >::stream(s, indent + "    ", v.edge[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_EXAMPLE_MESSAGE_TOPOLOGICALMAP_H
