// Generated by gencpp from file node_example/ViewTemplate.msg
// DO NOT EDIT!


#ifndef NODE_EXAMPLE_MESSAGE_VIEWTEMPLATE_H
#define NODE_EXAMPLE_MESSAGE_VIEWTEMPLATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace node_example
{
template <class ContainerAllocator>
struct ViewTemplate_
{
  typedef ViewTemplate_<ContainerAllocator> Type;

  ViewTemplate_()
    : header()
    , current_id(0)
    , relative_rad(0.0)  {
    }
  ViewTemplate_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current_id(0)
    , relative_rad(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _current_id_type;
  _current_id_type current_id;

   typedef double _relative_rad_type;
  _relative_rad_type relative_rad;




  typedef boost::shared_ptr< ::node_example::ViewTemplate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_example::ViewTemplate_<ContainerAllocator> const> ConstPtr;

}; // struct ViewTemplate_

typedef ::node_example::ViewTemplate_<std::allocator<void> > ViewTemplate;

typedef boost::shared_ptr< ::node_example::ViewTemplate > ViewTemplatePtr;
typedef boost::shared_ptr< ::node_example::ViewTemplate const> ViewTemplateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_example::ViewTemplate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_example::ViewTemplate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_example

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'node_example': ['/home/younes/Images/ratslam_test/rospyy/src/node_example/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_example::ViewTemplate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_example::ViewTemplate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_example::ViewTemplate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_example::ViewTemplate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_example::ViewTemplate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_example::ViewTemplate_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_example::ViewTemplate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3978e682f73dc18ef3727352b92d92e";
  }

  static const char* value(const ::node_example::ViewTemplate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3978e682f73dc18ULL;
  static const uint64_t static_value2 = 0xef3727352b92d92eULL;
};

template<class ContainerAllocator>
struct DataType< ::node_example::ViewTemplate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_example/ViewTemplate";
  }

  static const char* value(const ::node_example::ViewTemplate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_example::ViewTemplate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint32 current_id\n\
float64 relative_rad\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::node_example::ViewTemplate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_example::ViewTemplate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current_id);
      stream.next(m.relative_rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ViewTemplate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_example::ViewTemplate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_example::ViewTemplate_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.current_id);
    s << indent << "relative_rad: ";
    Printer<double>::stream(s, indent + "  ", v.relative_rad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_EXAMPLE_MESSAGE_VIEWTEMPLATE_H
